# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [52]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [87]:
df = np.loadtxt('minutes_n_ingredients.csv',  dtype = np.int32, delimiter = ',', skiprows = 1)
print(df[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [88]:
print('Минимум: ', np.min(df, axis = 1))
print('Максимум: ', np.max(df, axis = 1))
print('Среднее арифметическое: ',np.mean(df, axis = 1))
print('Медиана: ', np.median(df, axis = 1))

Минимум:  [16  7  6 ... 15  4 14]
Максимум:  [127244  23891  94746 ... 498432 370915  81993]
Среднее арифметическое:  [ 42440.           7974.33333333  31587.33333333 ... 166170.66666667
 123641.33333333  27382.33333333]
Медиана:  [ 60.  25.  10. ...  65.   5. 140.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [89]:
result = df[:,1]
print(np.quantile(result, 0.75, axis = 0))
q = np.quantile(df[:,1], 0.75)
df[:,1] = np.clip(df[:,1], a_min=0, a_max=q)
df[:10]

65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14],
       [152828,     40,      7],
       [ 33941,     18,      9],
       [446597,     15,      5],
       [366174,      7,      9],
       [ 74205,     20,      7]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [90]:
result = df[:, 1:2]
print(np.sum(result == 0))
np.place(result, result < 1, 1)
print(result)

479
[[60]
 [25]
 [10]
 ...
 [65]
 [ 5]
 [65]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [91]:
print(len(np.unique(df[:, :1])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [92]:
unique, counts = np.unique(df[:,2], return_counts=True)
print(f'уникальных значений {len(unique)}')
dict(zip(counts, unique))

уникальных значений 37


{13: 1,
 926: 2,
 2895: 3,
 5515: 4,
 7913: 5,
 9376: 6,
 10628: 7,
 10951: 8,
 10585: 9,
 9591: 10,
 8297: 11,
 6605: 12,
 4997: 13,
 3663: 14,
 2595: 15,
 1767: 16,
 1246: 17,
 790: 18,
 573: 19,
 376: 20,
 217: 21,
 161: 22,
 105: 23,
 69: 24,
 50: 25,
 28: 26,
 16: 28,
 12: 30,
 3: 35,
 1: 39,
 2: 33}

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [93]:
df[df[:, 2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [94]:
print(np.max(df[:, 2] // df[:, 1]))

24


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [95]:
print(np.mean(df[np.argsort(df[:,1])][-100:, 2]))

9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [96]:
n = 10 
index = np.random.choice(df.shape[0], n, replace=False)  
print(df[index])

[[427236     25     11]
 [374999     20      5]
 [ 78588     65      6]
 [269624     10      5]
 [433304      5      5]
 [124962     35      4]
 [264590     60      8]
 [244517     55     11]
 [ 63199     55     14]
 [ 25174     20      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [97]:
print(df[df[:,2]<np.mean(df[:,2])].shape[0]/df.shape[0]*100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [98]:
ndf = np.c_[df, (df[:, 1] < 20) & (df[:,2] < 5)]
ndf

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [99]:
df[(df[:, 1] < 20) & (df[:,2] < 5)].size / df.size * 100

5.093

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [100]:
arr1 = df[df[:,1] < 10]
arr2 = df[(df[:,1] >= 10) & (df[:,1] < 20)]
arr3 = df[20 <= df[:,1]]
df = np.min([arr1.shape[0], arr2.shape[0], arr3.shape[0]])
res = np.array([arr1[:df], arr2[:df], arr3[:df]])
print(result.shape)
print(result)

(100000, 1)
[[60]
 [25]
 [10]
 ...
 [65]
 [ 5]
 [65]]
